dist: bionic
sudo: true
language: python
python:
  - "3.6"
  # - "3.7"  # test only the extremes
  # - "3.8"  # test only the extremes
  - "3.9"
cache:
  - pip
before_install:
  - wget --quiet
    --output-document=pandoc.deb
    https://github.com/jgm/pandoc/releases/download/2.11.1.1/pandoc-2.11.1.1-1-amd64.deb
  - sudo dpkg --install pandoc.deb
install:
  - pip install ".[webpage,dev]"
script:
  - pytest -m='integration or travis'
