dist: xenial
sudo: true
language: python
python:
  - "3.6"
  - "3.7"
cache:
  - pip
before_install:
  - wget --quiet https://github.com/jgm/pandoc/releases/download/2.7.2/pandoc-2.7.2-1-amd64.deb
  - sudo dpkg --install pandoc-2.7.2-1-amd64.deb
install:
  - pip install ".[all]"
  - python setup.py sdist bdist_wheel
script:
  - pytest
deploy:
  provider: pypi
  user: dhimmel
  password:
    secure: KFuV0ou/lmBbCj9dz13U/eJZ/mgYefk32BE+L9jiSBf4DPb8eagunpDWEnJThb1/8ULk4KIsY6LZA49UV9ZafipMSXsrO8+Bf2qH0XinJ7sPb9Isyb3yaLMDLzgxvCsDI9MoDGMQNd52RGJBsp5UDUViOv0hIJgVSmLn1F4tw+hXWQsN81zrkucq8ws2nlFVZLTkC+axpaQXxqrzJU2ODML7i2Q+zP4+rFfQRF/3uAnDQ/o08rtE4TeipKWrAyJMLdhBSzvCaiqqzSyttR6df2hkxU/rkeLF2qHmugpewShEXINfbACYapAzcIKd1lCzU9wqRXtczXjNkb4FMiuHha8yAxW6dKQjogbs64NLUaSUCDnidDy5UsOBxH0+55czJ2s2FJn4bEk6yVIJcLfPW9pE59ypzPVfFNRByqsCGhVlKGSQxx+mf17lZSKTtWM0434ZsOGx8C04ny4r7iwRVRGy7+0s5eMUYsvIKP2R3hog7gfDBHtU5LPYRsDnjIMXdWNQEagpDH3/f9qAQXqTLIcOx6Rmrw8tZYaRxHUb0iVlCsqueqO2CCSVsqaTaPTYpoF122neJqm8uU3AnWGoSeV0W5Lj0ZFlOtdywUYfCU8h67xdWMUMbpJcLkVJWJoXeGcamLSytS3sIF5xlKJeOetdfZaQ+stYQJhwblIMs0I=
  on:
    python: '3.6'
    repo: manubot/manubot
    tags: true
  distributions: sdist bdist_wheel
